# Generated by Django 5.0.1 on 2026-01-09 10:31

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager assigned to this employee (only for employees)",
                limit_choices_to={"role": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
