# Generated by Django 4.2.16 on 2026-03-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_create_company_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["company"], name="user_company_idx"),
        ),
    ]
