# Generated by Django 4.2.16 on 2026-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="joining_date",
            field=models.DateField(
                blank=True, help_text="Date when the user joined the company", null=True
            ),
        ),
    ]
