# Generated by Django 4.2.16 on 2026-04-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_add_joining_date_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="Job title or designation of the user",
                max_length=100,
                null=True,
            ),
        ),
    ]
