# Generated by Django 4.2.16 on 2026-05-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
        ("accounts", "0016_invitetoken_add_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team this user belongs to (for ASE Technologies)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                blank=True,
                help_text="Blood group (e.g. A+, O-)",
                max_length=5,
                null=True,
            ),
        ),
    ]
