# Generated by Django 4.2.16 on 2026-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_user_team_alter_user_blood_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("team_lead", "Team Lead"),
                    ("employee", "Employee"),
                    ("hr", "HR"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
