# Generated by Django 4.2.16 on 2026-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_add_team_lead_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("team_lead", "Team Lead"),
                    ("employee", "Employee"),
                    ("hr", "HR"),
                    ("bre", "Business Research Executive"),
                    ("boe", "Business Outreach Executive"),
                    ("cre", "Client Research Executive"),
                    ("marketing_lead", "Marketing Team Lead"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
