# Generated by Django 4.2.16 on 2026-05-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_add_marketing_team_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitetoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("bre", "Business Research Executive"),
                    ("boe", "Business Outreach Executive"),
                    ("cre", "Client Research Executive"),
                    ("marketing_lead", "Marketing Team Lead"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
