# Generated by Django 4.2.16 on 2026-05-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_update_marketing_category_choices"),
        ("accounts", "0021_revert_marketing_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitetoken",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team to assign the new user to (for ASE Technologies)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_tokens",
                to="teams.team",
            ),
        ),
    ]
