# Generated by Django 4.2.16 on 2026-03-23 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0004_remove_pushsubscription_and_sent_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=500, unique=True)),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "push_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_company_b64cff_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
