# Generated by Django 4.2.16 on 2026-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_readd_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("leave_request", "Leave Request"),
                    ("leave_status", "Leave Status Update"),
                    ("leave_approved", "Leave Approved"),
                    ("leave_rejected", "Leave Rejected"),
                    ("leave_pending", "Leave Pending"),
                    ("announcement", "Announcement"),
                    ("task_assigned", "Task Assigned"),
                    ("task_updated", "Task Updated"),
                    ("project_updated", "Project Updated"),
                    ("lead_assigned", "Lead Assigned"),
                    ("customer_updated", "Customer Updated"),
                    ("system_alert", "System Alert"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
