# Generated by Django 4.2.7 on 2026-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.URLField(blank=True, help_text="Cover image URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="photos",
            field=models.TextField(blank=True, help_text="JSON array of photo URLs"),
        ),
    ]
