# Generated by Django 4.2.7 on 2026-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_cover_image_project_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plan_image",
            field=models.URLField(blank=True, help_text="Plan/Blueprint image URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="project_image",
            field=models.URLField(
                blank=True, help_text="Project completion/progress image URL"
            ),
        ),
    ]
