# Generated by Django 4.2.7 on 2026-01-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_add_plan_and_project_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="project",
            name="plan_image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_image",
        ),
        migrations.AddField(
            model_name="project",
            name="blueprint_image",
            field=models.URLField(blank=True, help_text="Blueprint/Plan image URL"),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.URLField(blank=True, help_text="Cover/Project image URL"),
        ),
    ]
