# Generated by Django 4.2.7 on 2026-01-29 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_simplify_project_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="amenities",
            field=models.JSONField(
                blank=True, default=list, help_text="List of amenities"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="blueprintImage",
            field=models.URLField(blank=True, help_text="Blueprint/Plan image URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="coverImage",
            field=models.URLField(blank=True, help_text="Cover/Project image URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="launchDate",
            field=models.DateField(
                blank=True, help_text="Project launch date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="project",
            name="nearbyLandmarks",
            field=models.JSONField(
                blank=True, default=list, help_text="List of nearby landmarks"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="possessionDate",
            field=models.DateField(
                blank=True, help_text="Expected possession date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priceMax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum price in rupees",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priceMin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum price in rupees",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="towerDetails",
            field=models.TextField(blank=True, help_text="Tower/Building details"),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("villa", "Villa"),
                    ("apartment", "Apartment"),
                    ("plots", "Plots"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="blueprint_image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
