# Generated by Django 4.2.7 on 2026-01-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_options_project_amenities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(max_length=300),
        ),
    ]
