# Generated by Django 4.2.7 on 2026-02-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("pre_launch", "Pre Launch"),
                    ("launch", "Launch"),
                    ("under_construction", "Under Construction"),
                    ("mid_stage", "Mid Stage"),
                    ("ready_to_go", "Ready to Go"),
                ],
                default="pre_launch",
                max_length=20,
            ),
        ),
    ]
