# Generated by Django 4.2.16 on 2026-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("projects", "0010_convert_availability_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this project belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["company"], name="projects_pr_company_3a6b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["company", "created_at"], name="projects_pr_company_29f4d9_idx"
            ),
        ),
    ]
