# Generated by Django 4.2.16 on 2026-03-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Birthday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Employee's birth date (year will be used for age calculation)"
                    ),
                ),
                (
                    "show_age",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to show age in birthday announcements",
                    ),
                ),
                (
                    "announce_birthday",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to create automatic birthday announcements",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="HR/Admin who added this birthday",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_birthdays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        help_text="Employee whose birthday is being recorded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Birthday",
                "verbose_name_plural": "Birthdays",
                "db_table": "birthdays",
                "ordering": ["employee__first_name", "employee__last_name"],
            },
        ),
        migrations.CreateModel(
            name="BirthdayAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcement_date",
                    models.DateField(
                        help_text="Date when the birthday announcement was created"
                    ),
                ),
                (
                    "announcement_id",
                    models.IntegerField(help_text="ID of the created announcement"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "birthday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="birthdays.birthday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Birthday Announcement",
                "verbose_name_plural": "Birthday Announcements",
                "db_table": "birthday_announcements",
                "ordering": ["-announcement_date"],
                "unique_together": {("birthday", "announcement_date")},
            },
        ),
    ]
