# Generated by Django 4.2.16 on 2026-01-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("site_visit", "Site Visit"),
                    ("family_visit", "Family Visit"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
