# Generated by Django 4.2.7 on 2026-02-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("site_visit", "Site Visit"),
                    ("family_visit", "Family Visit"),
                    ("perfect_family_visit", "Perfect Family Visit"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
