# Generated by Django 4.2.16 on 2026-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("tasks", "0006_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this task belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["company"], name="tasks_task_company_4e1a1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["company", "status"], name="tasks_task_company_c23f28_idx"
            ),
        ),
    ]
