# Generated by Django 4.2.16 on 2026-03-10 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="task",
            name="task_company_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="task_company_assigned_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="task_company_due_idx",
        ),
    ]
