# Generated by Django 4.2.16 on 2026-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
