# Generated by Django 4.2.16 on 2026-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("customers", "0003_update_no_response_to_not_interested"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this customer belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company"], name="customers_c_company_1b63a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company", "created_at"], name="customers_c_company_b59746_idx"
            ),
        ),
    ]
