# Generated by Django 4.2.16 on 2026-03-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="customer_company_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customer_company_assigned_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customer_company_scheduled_idx",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_converted"], name="customers_c_is_conv_5be987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company", "is_converted"],
                name="customers_c_company_4fadff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["call_status"], name="customers_c_call_st_b6b829_idx"
            ),
        ),
    ]
