# Generated by Django 4.2.16 on 2026-03-09 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_make_company_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0007_add_conversion_audit_log_and_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("convert_single", "Single Conversion"),
                            ("convert_bulk", "Bulk Conversion"),
                            ("conversion_failed", "Conversion Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("customer_id", models.IntegerField()),
                ("customer_phone", models.CharField(max_length=20)),
                ("customer_name", models.CharField(max_length=255)),
                ("lead_id", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_audits",
                        to="accounts.company",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "created_at"],
                        name="customers_c_company_55226a_idx",
                    ),
                    models.Index(
                        fields=["customer_id"], name="customers_c_custome_3f2739_idx"
                    ),
                    models.Index(
                        fields=["lead_id"], name="customers_c_lead_id_c2bb37_idx"
                    ),
                    models.Index(
                        fields=["performed_by"], name="customers_c_perform_ec73ed_idx"
                    ),
                ],
            },
        ),
    ]
