# Generated by Django 4.2.16 on 2026-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        ("customers", "0008_add_conversion_audit_log_and_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("phone", "company")},
        ),
    ]
