# Generated by Django 4.2.16 on 2026-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0009_alter_customer_phone_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["company", "call_status"], name="customers_c_company_dad00e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["assigned_to"], name="customers_c_assigne_583fe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["created_by"], name="customers_c_created_951bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customers_c_phone_8493fa_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customers_c_name_f018e2_idx"),
        ),
    ]
