# Generated by Django 4.2.16 on 2026-04-03 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("hot", "Hot"),
                            ("warm", "Warm"),
                            ("cold", "Cold"),
                            ("not_interested", "Not Interested"),
                            ("reminder", "Reminder"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="website", max_length=100)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_leads",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_created_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CapitalCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("not_answered", "Not Answered"),
                            ("busy", "Busy"),
                            ("not_interested", "Not Interested"),
                            ("custom", "Custom"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "custom_call_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("call_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_converted", models.BooleanField(default=False)),
                (
                    "converted_lead_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_assigned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_customers",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CapitalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("site_visit", "Site Visit"),
                            ("family_visit", "Family Visit"),
                            ("perfect_family_visit", "Perfect Family Visit"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="in_progress",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_tasks",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="capital.capitallead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="capital_cap_company_b7ab25_idx"
                    ),
                    models.Index(
                        fields=["status"], name="capital_cap_status_f21602_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="capital_cap_assigne_fbb1a1_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="capitallead",
            index=models.Index(
                fields=["company"], name="capital_cap_company_f87234_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capitallead",
            index=models.Index(fields=["status"], name="capital_cap_status_953e7a_idx"),
        ),
        migrations.AddIndex(
            model_name="capitallead",
            index=models.Index(
                fields=["assigned_to"], name="capital_cap_assigne_527a6f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="capitallead",
            unique_together={("phone", "company")},
        ),
        migrations.AddIndex(
            model_name="capitalcustomer",
            index=models.Index(
                fields=["company"], name="capital_cap_company_b589c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capitalcustomer",
            index=models.Index(
                fields=["call_status"], name="capital_cap_call_st_941139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capitalcustomer",
            index=models.Index(
                fields=["assigned_to"], name="capital_cap_assigne_da3797_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="capitalcustomer",
            unique_together={("phone", "company")},
        ),
    ]
