# Generated by Django 4.2.16 on 2026-04-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                ("aadhaar_number", models.CharField(blank=True, max_length=12)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("gst_registration", "GST Registration"),
                            ("gst_filing", "GST Filing"),
                            ("msme_registration", "MSME Registration"),
                            ("itr_filing", "Income Tax Filing"),
                            ("itr_notice", "Income Tax Notice"),
                            ("company_registration", "Company Registration"),
                            ("trademark", "Trademark Registration"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("financial_year", models.CharField(blank=True, max_length=10)),
                (
                    "service_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("documents_pending", "Documents Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="inquiry",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_assigned_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_services",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_created_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="capital_cap_company_618aaa_idx"
                    ),
                    models.Index(
                        fields=["status"], name="capital_cap_status_78cb2e_idx"
                    ),
                    models.Index(
                        fields=["service_type"], name="capital_cap_service_002621_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="capital_cap_assigne_d205d1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Loan"),
                            ("business", "Business Loan"),
                            ("home", "Home Loan"),
                            ("vehicle", "Vehicle Loan"),
                            ("education", "Education Loan"),
                            ("gold", "Gold Loan"),
                            ("mortgage", "Mortgage Loan"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("tenure_months", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("documents_pending", "Documents Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="inquiry",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_assigned_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_loans",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_created_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="capital_cap_company_a0a883_idx"
                    ),
                    models.Index(
                        fields=["status"], name="capital_cap_status_9ef337_idx"
                    ),
                    models.Index(
                        fields=["loan_type"], name="capital_cap_loan_ty_a16d68_idx"
                    ),
                    models.Index(
                        fields=["assigned_to"], name="capital_cap_assigne_b0eaf6_idx"
                    ),
                ],
            },
        ),
    ]
