# Generated by Django 4.2.16 on 2026-04-03 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        ("capital", "0005_capitaltask_link_loan_service"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="capitalloan",
            unique_together={("phone", "loan_type", "company")},
        ),
        migrations.AlterUniqueTogether(
            name="capitalservice",
            unique_together={("phone", "service_type", "financial_year", "company")},
        ),
    ]
