# Generated by Django 4.2.16 on 2026-04-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        ("capital", "0006_add_unique_constraints_loans_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankLoanStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted to Bank"),
                            ("submitted", "Submitted to Bank"),
                            ("under_review", "Under Bank Review"),
                            (
                                "additional_docs_required",
                                "Additional Documents Required",
                            ),
                            ("approved", "Approved by Bank"),
                            ("rejected", "Rejected by Bank"),
                            ("disbursed", "Loan Disbursed"),
                        ],
                        default="not_submitted",
                        max_length=30,
                    ),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "approved_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "approved_tenure_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("bank_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_status",
                        to="capital.capitalloan",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity Proof (Aadhaar/PAN/Passport)"),
                            ("address", "Address Proof"),
                            ("income", "Income Proof (Salary Slips/ITR)"),
                            ("bank_statement", "Bank Statement (6 months)"),
                            ("business_proof", "Business Proof (GST/Registration)"),
                            ("property_docs", "Property Documents"),
                            ("photo", "Passport Size Photo"),
                            ("form16", "Form 16"),
                            ("itr", "Income Tax Returns"),
                            ("balance_sheet", "Balance Sheet"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="capital.capitalloan",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["document_type"],
                "unique_together": {("loan", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="LoanApprovalStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("initial_review", "Initial Review"),
                            ("document_verification", "Document Verification"),
                            ("credit_check", "Credit Check"),
                            ("manager_approval", "Manager Approval"),
                            ("bank_submission", "Bank Submission"),
                            ("bank_processing", "Bank Processing"),
                            ("final_approval", "Final Approval"),
                            ("disbursement", "Disbursement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_stages",
                        to="capital.capitalloan",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("loan", "stage")},
            },
        ),
        migrations.CreateModel(
            name="BankInterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Loan"),
                            ("business", "Business Loan"),
                            ("home", "Home Loan"),
                            ("vehicle", "Vehicle Loan"),
                            ("education", "Education Loan"),
                            ("gold", "Gold Loan"),
                            ("mortgage", "Mortgage Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "max_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "processing_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("min_tenure_months", models.PositiveIntegerField(default=12)),
                ("max_tenure_months", models.PositiveIntegerField(default=360)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_rates",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["bank_name", "loan_type"],
                "unique_together": {("bank_name", "loan_type", "company")},
            },
        ),
    ]
