# Generated by Django 4.2.7 on 2026-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holidays", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="holiday",
            options={"ordering": ["start_date"]},
        ),
        migrations.RenameField(
            model_name="holiday",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("name", "start_date")},
        ),
        migrations.AddField(
            model_name="holiday",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Leave blank for single-day holiday", null=True
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional holiday image",
                null=True,
                upload_to="holidays/",
            ),
        ),
    ]
