# Generated by Django 4.2.16 on 2026-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        (
            "holidays",
            "0002_alter_holiday_options_rename_date_holiday_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this holiday belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holidays",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["company"], name="holidays_ho_company_894075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["company", "start_date"], name="holidays_ho_company_acdb58_idx"
            ),
        ),
    ]
