# Generated by Django 4.2.16 on 2026-03-10 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("holidays", "0005_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="holiday",
            name="holiday_company_type_idx",
        ),
    ]
