# Generated by Django 4.2.16 on 2026-03-11 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_make_company_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASECustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Company or business name", max_length=255
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Primary contact person name", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary phone number", max_length=20),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Company website URL", null=True
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance"),
                            ("retail", "Retail & E-commerce"),
                            ("real_estate", "Real Estate"),
                            ("education", "Education"),
                            ("hospitality", "Hospitality & Tourism"),
                            ("manufacturing", "Manufacturing"),
                            ("professional_services", "Professional Services"),
                            ("non_profit", "Non-Profit"),
                            ("automotive", "Automotive"),
                            ("food_beverage", "Food & Beverage"),
                            ("fashion", "Fashion & Beauty"),
                            ("sports_fitness", "Sports & Fitness"),
                            ("entertainment", "Entertainment & Media"),
                            ("other", "Other"),
                        ],
                        help_text="Industry sector",
                        max_length=50,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        help_text="Number of employees",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "annual_revenue",
                    models.CharField(
                        blank=True,
                        help_text="Annual revenue range",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "service_interests",
                    models.JSONField(
                        default=list, help_text="List of interested services"
                    ),
                ),
                (
                    "current_marketing_spend",
                    models.CharField(
                        blank=True,
                        help_text="Current monthly marketing spend",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_1k", "Under $1,000/month"),
                            ("1k_5k", "$1,000 - $5,000/month"),
                            ("5k_10k", "$5,000 - $10,000/month"),
                            ("10k_25k", "$10,000 - $25,000/month"),
                            ("25k_50k", "$25,000 - $50,000/month"),
                            ("over_50k", "Over $50,000/month"),
                            ("project_based", "Project-based"),
                            ("custom", "Custom"),
                        ],
                        help_text="Budget range for services",
                        max_length=50,
                    ),
                ),
                (
                    "custom_budget",
                    models.CharField(
                        blank=True,
                        help_text="Custom budget if 'custom' selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "has_website",
                    models.BooleanField(
                        default=True, help_text="Does the company have a website?"
                    ),
                ),
                (
                    "has_social_media",
                    models.BooleanField(
                        default=False, help_text="Active on social media?"
                    ),
                ),
                (
                    "current_seo_agency",
                    models.CharField(
                        blank=True,
                        help_text="Current SEO/Marketing agency",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "marketing_goals",
                    models.TextField(
                        blank=True,
                        help_text="Primary marketing goals and objectives",
                        null=True,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        help_text="How did they find us?",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        help_text="Referral source if applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiating", "Negotiating"),
                            ("active", "Active Client"),
                            ("on_hold", "On Hold"),
                            ("inactive", "Inactive"),
                            ("lost", "Lost"),
                        ],
                        default="prospect",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level",
                        max_length=10,
                    ),
                ),
                (
                    "first_contact_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of first contact", null=True
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of last contact", null=True
                    ),
                ),
                (
                    "next_follow_up",
                    models.DateTimeField(
                        blank=True, help_text="Next follow-up date", null=True
                    ),
                ),
                (
                    "proposal_sent_date",
                    models.DateTimeField(
                        blank=True, help_text="Date proposal was sent", null=True
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateTimeField(
                        blank=True, help_text="Contract start date", null=True
                    ),
                ),
                (
                    "estimated_project_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated project value in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_retainer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly retainer amount",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes and comments", null=True
                    ),
                ),
                (
                    "communication_log",
                    models.JSONField(default=list, help_text="Log of communications"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned team member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ase_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this customer belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ase_customers",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_ase_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ASE Customer",
                "verbose_name_plural": "ASE Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ASECustomerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("proposal", "Proposal Sent"),
                            ("contract", "Contract Signed"),
                            ("status_change", "Status Change"),
                            ("note", "Note Added"),
                            ("follow_up", "Follow-up Scheduled"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("activity_date", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="ase_customers.asecustomer",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ase_customer_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ASE Customer Activity",
                "verbose_name_plural": "ASE Customer Activities",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["company"], name="ase_custome_company_2e01f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(fields=["status"], name="ase_custome_status_1f01d7_idx"),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["assigned_to"], name="ase_custome_assigne_795c07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["industry"], name="ase_custome_industr_27d83f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["budget_range"], name="ase_custome_budget__aef5cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["priority"], name="ase_custome_priorit_929327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["company", "status"], name="ase_custome_company_c7d4ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["company", "created_at"], name="ase_custome_company_8d0260_idx"
            ),
        ),
    ]
