# Generated by Django 4.2.16 on 2026-03-11 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ("ase_customers", "0001_initial"),
    ]

    operations = [
        # Drop the old ASECustomerActivity table
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ase_customers_asecustomeractivity;",
            reverse_sql="-- No reverse operation"
        ),
        
        # Drop the old ASECustomer table
        migrations.RunSQL(
            "DROP TABLE IF EXISTS ase_customers_asecustomer;",
            reverse_sql="-- No reverse operation"
        ),
        
        # Create the new simplified ASECustomer table
        migrations.CreateModel(
            name='ASECustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=255)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('call_status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('busy', 'Busy'), ('not_interested', 'Not Interested'), ('custom', 'Custom')], default='pending', help_text='Call status', max_length=20)),
                ('custom_call_status', models.CharField(blank=True, help_text='Custom call status', max_length=100, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled call date', null=True)),
                ('call_date', models.DateTimeField(blank=True, help_text='Actual call date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Customer notes', null=True)),
                ('is_converted', models.BooleanField(default=False, help_text='Converted to lead')),
                ('converted_lead_id', models.CharField(blank=True, help_text='ID of converted lead', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assigned team member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ase_customers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company this customer belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ase_customers', to='accounts.company')),
                ('created_by', models.ForeignKey(help_text='User who created this customer', on_delete=django.db.models.deletion.CASCADE, related_name='created_ase_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ASE Customer',
                'verbose_name_plural': 'ASE Customers',
                'ordering': ['-created_at'],
            },
        ),
        
        # Add indexes
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS ase_customers_asecustomer_company_id_idx ON ase_customers_asecustomer(company_id);
            CREATE INDEX IF NOT EXISTS ase_customers_asecustomer_call_status_idx ON ase_customers_asecustomer(call_status);
            CREATE INDEX IF NOT EXISTS ase_customers_asecustomer_assigned_to_id_idx ON ase_customers_asecustomer(assigned_to_id);
            CREATE INDEX IF NOT EXISTS ase_customers_asecustomer_company_call_status_idx ON ase_customers_asecustomer(company_id, call_status);
            CREATE INDEX IF NOT EXISTS ase_customers_asecustomer_company_created_at_idx ON ase_customers_asecustomer(company_id, created_at);
            CREATE INDEX IF NOT EXISTS ase_customers_asecustomer_is_converted_idx ON ase_customers_asecustomer(is_converted);
            """,
            reverse_sql="-- No reverse operation"
        ),
    ]
