# Generated by Django 4.2.16 on 2026-03-18 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_customers", "0005_add_custom_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("not_answered", "Not Answered"),
                            ("busy", "Busy"),
                            ("not_interested", "Not Interested"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("called_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-called_at"],
            },
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["company"], name="ase_custome_company_2e01f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["call_status"], name="ase_custome_call_st_754e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["assigned_to"], name="ase_custome_assigne_795c07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["company", "call_status"], name="ase_custome_company_ac3ddd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["company", "created_at"], name="ase_custome_company_8d0260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asecustomer",
            index=models.Index(
                fields=["is_converted"], name="ase_custome_is_conv_a139dc_idx"
            ),
        ),
        migrations.AddField(
            model_name="calllog",
            name="called_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calllog",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_logs",
                to="ase_customers.asecustomer",
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["customer", "called_at"], name="ase_custome_custome_71f3fa_idx"
            ),
        ),
    ]
