# Generated by Django 4.2.16 on 2026-03-18 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        ("ase_customers", "0006_calllog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asecustomer",
            unique_together={("phone", "company")},
        ),
    ]
