# Generated by Django 4.2.16 on 2026-03-30 10:05

from django.db import migrations, connection


def rename_index_if_exists(apps, schema_editor):
    """Safely rename index only if old name exists."""
    # SQLite doesn't support RENAME INDEX — skip on SQLite
    if schema_editor.connection.vendor == 'sqlite':
        return
    try:
        schema_editor.execute(
            'ALTER INDEX ase_cust_note_customer_idx RENAME TO ase_custome_custome_52fdbe_idx'
        )
    except Exception:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("ase_customers", "0008_customernote"),
    ]

    operations = [
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
