# Generated by Django 4.2.16 on 2026-01-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="document_url",
        ),
        migrations.AddField(
            model_name="leave",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="leave_documents/"),
        ),
    ]
