# Generated by Django 4.2.16 on 2026-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("leaves", "0002_remove_leave_document_url_leave_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this leave belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leaves",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["company"], name="leaves_leav_company_d11dd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["company", "created_at"], name="leaves_leav_company_dfa0cb_idx"
            ),
        ),
    ]
