# Generated by Django 4.2.16 on 2026-03-10 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0005_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="leave",
            name="leave_company_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="leave",
            name="leave_company_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="leave",
            name="leave_company_start_idx",
        ),
    ]
