# Generated by Django 4.2.7 on 2026-02-06 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("announcements", "0002_announcementread"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="assigned_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific employees who can see this announcement. If empty, uses target_roles.",
                related_name="assigned_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
