# Generated by Django 4.2.16 on 2026-03-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("announcements", "0003_announcement_assigned_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this announcement belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcements",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["company"], name="announcemen_company_ae17b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["company", "created_at"], name="announcemen_company_ddc8c6_idx"
            ),
        ),
    ]
