# Generated by Django 4.2.16 on 2026-03-10 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0006_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcement_company_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcement_company_priority_idx",
        ),
    ]
