# Generated by Django 4.2.16 on 2026-03-12 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_add_document_fields"),
        (
            "announcements",
            "0007_remove_announcement_announcement_company_active_idx_and_more",
        ),
    ]

    operations = []
