# Generated by Django 4.2.16 on 2026-03-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_make_company_required"),
        ("announcements", "0008_merge_20260312_1206"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcemen_company_ddc8c6_idx",
        ),
        migrations.AddField(
            model_name="announcement",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Companies this announcement is sent to",
                related_name="announcements",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy single company field (deprecated)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcements_legacy",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["created_at"], name="announcemen_created_40a59f_idx"
            ),
        ),
    ]
