# Generated by Django 4.2.16 on 2026-03-30 10:05

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0010_add_document_url_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Optional document attachment (PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, TXT) or image (JPG, PNG, GIF, BMP, SVG, WEBP)",
                null=True,
                upload_to=announcements.models.announcement_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="document_name",
            field=models.CharField(
                blank=True,
                help_text="Display name for the document/image (required for URL-based documents)",
                max_length=255,
                null=True,
            ),
        ),
    ]
