# Generated by Django 4.2.16 on 2026-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="follow_up_date",
            field=models.DateTimeField(
                blank=True, help_text="Date and time for follow-up reminder", null=True
            ),
        ),
    ]
