# Generated by Django 4.2.16 on 2026-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_add_follow_up_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("hot", "Hot"),
                    ("warm", "Warm"),
                    ("cold", "Cold"),
                    ("not_interested", "Not Interested"),
                    ("reminder", "Reminder"),
                ],
                default="warm",
                max_length=20,
            ),
        ),
    ]
