# Generated by Django 4.2.16 on 2026-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0006_add_reminder_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="notes",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="company",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="priority",
        ),
        migrations.AddField(
            model_name="lead",
            name="assigned_project",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="bhk_requirement",
            field=models.CharField(
                choices=[
                    ("1", "1 BHK"),
                    ("2", "2 BHK"),
                    ("3", "3 BHK"),
                    ("4", "4 BHK"),
                    ("5+", "5+ BHK"),
                ],
                default="2",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_max",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="lead",
            name="description",
            field=models.TextField(blank=True, help_text="Lead description and notes"),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("villa", "Villa"),
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("plot", "Plot"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("walk_in", "Walk-in"),
                    ("website", "Website"),
                    ("referral", "Referral"),
                ],
                default="website",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("hot", "Hot"),
                    ("warm", "Warm"),
                    ("cold", "Cold"),
                    ("not_interested", "Not Interested"),
                    ("reminder", "Reminder"),
                ],
                default="hot",
                max_length=20,
            ),
        ),
    ]
