# Generated by Django 4.2.16 on 2026-01-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_alter_lead_options_rename_notes_lead_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                default="website",
                help_text="Lead source - can be predefined or custom",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("hot", "Hot"),
                    ("warm", "Warm"),
                    ("cold", "Cold"),
                    ("not_interested", "Not Interested"),
                    ("reminder", "Reminder"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
