# Generated by Django 4.2.16 on 2026-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_alter_lead_source_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assigned_projects",
            field=models.JSONField(
                blank=True, default=list, help_text="List of assigned project IDs"
            ),
        ),
    ]
