# Generated by Django 4.2.7 on 2026-02-03 11:49

from django.db import migrations


def update_lead_statuses(apps, schema_editor):
    """
    Update existing lead statuses to match frontend expectations:
    - contacted -> warm
    - qualified -> hot  
    - converted -> not_interested (completed leads)
    - new -> new (keep as is)
    """
    Lead = apps.get_model('leads', 'Lead')
    
    # Status mapping from old to new
    status_mapping = {
        'contacted': 'warm',
        'qualified': 'hot',
        'converted': 'not_interested',  # Converted leads are essentially done/not actively pursued
        'new': 'new',  # Keep as is
    }
    
    # Update leads with old statuses
    for old_status, new_status in status_mapping.items():
        updated_count = Lead.objects.filter(status=old_status).update(status=new_status)
        if updated_count > 0:
            print(f"Updated {updated_count} leads from '{old_status}' to '{new_status}'")


def reverse_lead_statuses(apps, schema_editor):
    """
    Reverse the status changes if needed
    """
    Lead = apps.get_model('leads', 'Lead')
    
    # Reverse mapping
    reverse_mapping = {
        'warm': 'contacted',
        'hot': 'qualified',
        'not_interested': 'converted',
        'new': 'new',
    }
    
    for new_status, old_status in reverse_mapping.items():
        updated_count = Lead.objects.filter(status=new_status).update(status=old_status)
        if updated_count > 0:
            print(f"Reverted {updated_count} leads from '{new_status}' to '{old_status}'")


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0009_lead_assigned_projects"),
    ]

    operations = [
        migrations.RunPython(update_lead_statuses, reverse_lead_statuses),
    ]
