# Generated by Django 4.2.7 on 2026-02-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0010_update_lead_statuses"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="leads_lead_phone_709d42_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="leads_lead_status_e23abe_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["source"], name="leads_lead_source_200868_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to"], name="leads_lead_assigne_3f8857_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_by"], name="leads_lead_created_e6e1a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["created_at"], name="leads_lead_created_302c6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["follow_up_date"], name="leads_lead_follow__064bf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "assigned_to"], name="leads_lead_status_a53442_idx"
            ),
        ),
    ]
