# Generated by Django 4.2.16 on 2026-03-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("leads", "0011_lead_leads_lead_phone_709d42_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this lead belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company"], name="leads_lead_company_01ed76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company", "created_at"], name="leads_lead_company_222d77_idx"
            ),
        ),
    ]
