# Generated by Django 4.2.16 on 2026-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0014_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lead",
            name="lead_company_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="lead_company_assigned_idx",
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="lead_company_followup_idx",
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company", "source"], name="leads_lead_company_376c4f_idx"
            ),
        ),
    ]
