# Generated by Django 4.2.16 on 2026-04-02 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_make_company_optional_for_admin_hr"),
        ("leads", "0015_add_customer_conversion_source_and_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lead",
            unique_together={("phone", "company")},
        ),
    ]
