# Generated by Django 4.2.16 on 2026-05-04 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0016_invitetoken_add_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Team name (e.g., 'Frontend Development', 'SEO Team')",
                        max_length=100,
                    ),
                ),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Team"),
                            ("marketing", "Marketing Team"),
                            ("sales", "Sales Team"),
                            ("support", "Support Team"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="Type of team",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Team description and responsibilities",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this team currently active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this team belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="accounts.company",
                    ),
                ),
                (
                    "team_lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team leader/manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["team_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["company", "team_type"],
                        name="teams_team_company_1d843b_idx",
                    ),
                    models.Index(
                        fields=["company", "is_active"],
                        name="teams_team_company_482832_idx",
                    ),
                ],
                "unique_together": {("name", "company")},
            },
        ),
    ]
