# Generated by Django 4.2.16 on 2026-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_type",
            field=models.CharField(
                choices=[
                    ("technical", "Technical Team"),
                    ("marketing", "Marketing Team"),
                ],
                help_text="Type of team",
                max_length=20,
            ),
        ),
    ]
