# Generated by Django 4.2.16 on 2026-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_team_team_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="marketing_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bre", "Business Research Executive (BRE)"),
                    ("boe", "Business Outreach Executive (BOE)"),
                    ("cre", "Client Research Executive (CRE)"),
                    ("marketing_lead", "Marketing Team Lead"),
                    ("general", "General Marketing"),
                ],
                help_text="Marketing team category (only for marketing teams)",
                max_length=20,
                null=True,
            ),
        ),
    ]
