# Generated by Django 4.2.16 on 2026-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aselead",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Primary email address", max_length=254, null=True
            ),
        ),
    ]
