# Generated by Django 4.2.16 on 2026-03-11 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0005_add_custom_services"),
    ]

    operations = [
        # Skip this migration for now to avoid index issues
        # The budget_range field will be ignored in the serializer
    ]
