# Generated by Django 4.2.16 on 2026-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0006_auto_20260311_1739"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aselead",
            name="ase_leads_a_budget__88a2a3_idx",
        ),
        migrations.RemoveField(
            model_name="aselead",
            name="budget_range",
        ),
        migrations.RemoveField(
            model_name="aselead",
            name="custom_budget",
        ),
        migrations.AddField(
            model_name="aselead",
            name="budget_amount",
            field=models.CharField(
                blank=True,
                help_text="Budget amount for services",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aselead",
            name="estimated_project_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated project value in INR",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aselead",
            name="monthly_retainer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly retainer amount in INR",
                max_digits=8,
                null=True,
            ),
        ),
    ]
