# Generated by Django 4.2.16 on 2026-05-06 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_leads", "0008_duplicate_phone_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="aselead",
            name="contacted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="BOE who made first contact with this lead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacted_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="deal_closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when deal was closed (won/lost)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="first_contact_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when BOE made first contact", null=True
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="CRE managing this lead through proposal and closing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="proposal_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when CRE sent proposal", null=True
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="research_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when BRE completed research and qualification",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="researched_by",
            field=models.ForeignKey(
                blank=True,
                help_text="BRE who researched and qualified this lead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="researched_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
