# Generated by Django 4.2.16 on 2026-05-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0009_aselead_contacted_by_aselead_deal_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aselead",
            name="response_time_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average response time in hours",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="total_calls_made",
            field=models.IntegerField(
                default=0, help_text="Total number of calls made to this lead"
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="total_emails_sent",
            field=models.IntegerField(
                default=0, help_text="Total number of emails sent to this lead"
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="total_meetings_held",
            field=models.IntegerField(
                default=0, help_text="Total number of meetings held with this lead"
            ),
        ),
    ]
