# Generated by Django 4.2.16 on 2026-05-06 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ase_leads",
            "0010_aselead_response_time_hours_aselead_total_calls_made_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aselead",
            name="disqualification_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for disqualifying the lead (if applicable)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="lead_score",
            field=models.IntegerField(
                default=0,
                help_text="Lead quality score from 0-100 (assigned by BRE during qualification)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="qualification_notes",
            field=models.TextField(
                blank=True,
                help_text="BRE notes on lead qualification, research findings, and quality assessment",
                null=True,
            ),
        ),
    ]
