# Generated by Django 4.2.16 on 2026-05-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ase_leads",
            "0011_aselead_disqualification_reason_aselead_lead_score_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aselead",
            name="engagement_level",
            field=models.CharField(
                choices=[
                    ("cold", "Cold"),
                    ("warm", "Warm"),
                    ("hot", "Hot"),
                    ("very_hot", "Very Hot"),
                ],
                default="cold",
                help_text="Current engagement level of the lead",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="last_engagement_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time of last engagement with the lead",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aselead",
            name="last_engagement_type",
            field=models.CharField(
                blank=True,
                help_text="Type of last engagement (call, email, meeting, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ASELeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("note", "Note"),
                            ("status_change", "Status Change"),
                            ("assignment", "Assignment"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title or summary of the activity",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the activity",
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="Outcome or result of the activity",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "call_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the call in minutes",
                        null=True,
                    ),
                ),
                (
                    "call_outcome",
                    models.CharField(
                        blank=True,
                        help_text="Outcome of the call (answered, voicemail, no answer, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line of the email",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_opened",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email was opened by the recipient",
                    ),
                ),
                (
                    "email_clicked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether any links in the email were clicked",
                    ),
                ),
                (
                    "meeting_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled date and time of the meeting",
                        null=True,
                    ),
                ),
                (
                    "meeting_attendees",
                    models.JSONField(
                        default=list, help_text="List of meeting attendees"
                    ),
                ),
                (
                    "requires_followup",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this activity requires a follow-up",
                    ),
                ),
                (
                    "followup_date",
                    models.DateTimeField(
                        blank=True, help_text="Date when follow-up is due", null=True
                    ),
                ),
                (
                    "followup_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the follow-up has been completed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this activity was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this activity was last updated"
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="The lead this activity is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="ase_leads.aselead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ase_lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ASE Lead Activity",
                "verbose_name_plural": "ASE Lead Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "activity_type"],
                        name="ase_leads_a_lead_id_b144db_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="ase_leads_a_user_id_31a105_idx",
                    ),
                    models.Index(
                        fields=["requires_followup", "followup_date"],
                        name="ase_leads_a_require_86c91c_idx",
                    ),
                    models.Index(
                        fields=["lead", "-created_at"],
                        name="ase_leads_a_lead_id_bef152_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="ase_leads_a_activit_b2f888_idx",
                    ),
                ],
            },
        ),
    ]
