# Generated by Django 4.2.16 on 2026-05-06 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_leads", "0012_aselead_engagement_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASELeadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("call", "Make Call"),
                            ("email", "Send Email"),
                            ("meeting", "Schedule Meeting"),
                            ("research", "Research"),
                            ("proposal", "Prepare Proposal"),
                            ("followup", "Follow Up"),
                            ("other", "Other"),
                        ],
                        help_text="Type of task to be performed",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title or summary of the task", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the task",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Priority level of the task",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(help_text="When this task is due")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this task was completed", null=True
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a reminder has been sent for this task",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to send a reminder for this task",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this task was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this task was last updated"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="User assigned to complete this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ase_lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_ase_lead_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="The lead this task is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="ase_leads.aselead",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASE Lead Task",
                "verbose_name_plural": "ASE Lead Tasks",
                "ordering": ["due_date", "-priority"],
                "indexes": [
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="ase_leads_a_assigne_9b69e8_idx",
                    ),
                    models.Index(
                        fields=["lead", "status"], name="ase_leads_a_lead_id_d672f1_idx"
                    ),
                    models.Index(
                        fields=["due_date", "status"],
                        name="ase_leads_a_due_dat_6fc10c_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "due_date"],
                        name="ase_leads_a_assigne_42b1c3_idx",
                    ),
                    models.Index(
                        fields=["status", "priority", "due_date"],
                        name="ase_leads_a_status_ed8f06_idx",
                    ),
                ],
            },
        ),
    ]
