# Generated by Django 4.2.16 on 2026-05-08 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_revert_marketing_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_leads", "0014_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BREResearchData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Contact person name", max_length=255),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Phone number", max_length=20),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="City / Area / Location",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee assigned to this data (auto-assigned to creator initially)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bre_research_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this data belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bre_research_data",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="BRE employee who added this data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bre_research_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BRE Research Data",
                "verbose_name_plural": "BRE Research Data",
                "db_table": "ase_leads_breresearchdata",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "created_by"],
                        name="ase_leads_b_company_86988d_idx",
                    ),
                    models.Index(
                        fields=["company", "assigned_to"],
                        name="ase_leads_b_company_a5056d_idx",
                    ),
                    models.Index(
                        fields=["phone_number"], name="ase_leads_b_phone_n_c4fc6a_idx"
                    ),
                ],
                "unique_together": {("phone_number", "company")},
            },
        ),
    ]
