# Generated by Django 4.2.16 on 2026-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0015_create_breresearchdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="breresearchdata",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("assigned", "Assigned")],
                default="new",
                help_text="Status: new (unassigned) or assigned (given to BOE)",
                max_length=20,
            ),
        ),
    ]
