# Generated by Django 4.2.16 on 2026-05-09 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_leads", "0016_add_status_to_breresearchdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="breresearchdata",
            name="assigned_to_cre",
            field=models.ForeignKey(
                blank=True,
                help_text="CRE employee assigned after positive call",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bre_research_cre_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="breresearchdata",
            name="call_notes",
            field=models.TextField(
                blank=True, default="", help_text="Notes from BOE call"
            ),
        ),
        migrations.AddField(
            model_name="breresearchdata",
            name="call_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("called", "Called"),
                    ("positive", "Positive"),
                    ("negative", "Negative"),
                    ("no_answer", "No Answer"),
                    ("callback", "Call Back Later"),
                ],
                default="pending",
                help_text="Call status set by BOE employee",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="breresearchdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("assigned", "Assigned"),
                    ("converted", "Converted to Lead"),
                ],
                default="new",
                help_text="Status: new (unassigned), assigned (given to BOE), or converted (positive lead)",
                max_length=20,
            ),
        ),
    ]
