# Generated by Django 4.2.16 on 2026-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0017_add_boe_call_status_and_cre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breresearchdata",
            name="call_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("no_answer", "No Answer"),
                    ("callback", "Call Back Later"),
                    ("not_interested", "Not Interested"),
                    ("interested", "Interested"),
                ],
                default="pending",
                help_text="Call status set by BOE employee",
                max_length=20,
            ),
        ),
    ]
