# Generated by Django 4.2.16 on 2026-05-11 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_revert_marketing_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_leads", "0018_update_call_status_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOELead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("call_notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("assigned_cre", "Assigned to CRE"),
                            ("in_progress", "In Progress"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to_cre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boe_leads_cre_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boe_leads",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boe_leads_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_research",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original research data this lead came from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="ase_leads.breresearchdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOE Lead",
                "verbose_name_plural": "BOE Leads",
                "db_table": "ase_leads_boelead",
                "ordering": ["-created_at"],
            },
        ),
    ]
