# Generated by Django 4.2.16 on 2026-05-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0019_create_boe_lead_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aseleadtask",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="The lead this task is associated with",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="ase_leads.aselead",
            ),
        ),
    ]
