# Generated by Django 4.2.16 on 2026-05-14 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ase_leads", "0020_make_task_lead_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="aseleadtask",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who assigned this lead (BOE who assigned to CRE)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_ase_lead_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aseleadtask",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who closed/completed this task (CRE who converted to task)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_ase_lead_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="aseleadtask",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this task (BRE who created the original data)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_ase_lead_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="boelead",
            name="status",
            field=models.CharField(
                choices=[
                    ("interested", "Interested"),
                    ("assigned_cre", "Assigned to CRE"),
                    ("in_progress", "In Progress"),
                    ("converted", "Converted"),
                    ("completed", "Completed"),
                    ("lost", "Lost"),
                ],
                default="interested",
                max_length=20,
            ),
        ),
    ]
