# Generated by Django 4.2.16 on 2026-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0021_add_assigned_by_closed_by_to_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="boelead",
            name="task_created",
            field=models.BooleanField(
                default=False, help_text="Whether a task has been created for this lead"
            ),
        ),
    ]
