# Generated by Django 4.2.16 on 2026-06-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ase_leads", "0022_add_task_created_to_boelead"),
    ]

    operations = [
        migrations.AddField(
            model_name="aselead",
            name="custom_status",
            field=models.CharField(
                blank=True,
                help_text="Custom status text when status is 'custom'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aselead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New Lead"),
                    ("demo_done", "Demo Done"),
                    ("presentation", "Presentation"),
                    ("custom", "Custom"),
                ],
                default="new",
                help_text="Current status",
                max_length=20,
            ),
        ),
    ]
