# Generated by Django 5.0.1 on 2026-01-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_role", models.CharField(max_length=20)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("leads", "Leads"),
                            ("tasks", "Tasks"),
                            ("projects", "Projects"),
                            ("leaves", "Leaves"),
                            ("users", "Users"),
                            ("announcements", "Announcements"),
                            ("reports", "Reports"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("viewed", "Viewed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="activity_lo_user_id_fb0911_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="activity_lo_module_f20c87_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="activity_lo_action_50d146_idx",
                    ),
                ],
            },
        ),
    ]
