# Generated by Django 4.2.16 on 2026-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("created", "Created"),
                    ("update", "Update"),
                    ("updated", "Updated"),
                    ("delete", "Delete"),
                    ("deleted", "Deleted"),
                    ("view", "View"),
                    ("viewed", "Viewed"),
                    ("approve", "Approve"),
                    ("approved", "Approved"),
                    ("reject", "Reject"),
                    ("rejected", "Rejected"),
                    ("convert", "Convert"),
                    ("converted", "Converted"),
                    ("assign", "Assign"),
                    ("assigned", "Assigned"),
                    ("complete", "Complete"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="module",
            field=models.CharField(
                choices=[
                    ("leads", "Leads"),
                    ("customers", "Customers"),
                    ("tasks", "Tasks"),
                    ("projects", "Projects"),
                    ("leaves", "Leaves"),
                    ("users", "Users"),
                    ("announcements", "Announcements"),
                    ("reports", "Reports"),
                ],
                max_length=20,
            ),
        ),
    ]
