# Generated by Django 4.2.16 on 2026-03-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_company_to_user"),
        ("activity_logs", "0002_alter_activitylog_action_alter_activitylog_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this activity log belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_logs",
                to="accounts.company",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["company"], name="activity_lo_company_8f8e24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["company", "created_at"], name="activity_lo_company_5fc54d_idx"
            ),
        ),
    ]
