# Generated by Django 4.2.7 on 2026-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(default="ESWARI CONNECTS", max_length=100),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="URL to the application logo", null=True
                    ),
                ),
                (
                    "favicon_url",
                    models.URLField(
                        blank=True, help_text="URL to the favicon", null=True
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="152 45% 28%",
                        help_text='HSL format: "152 45% 28%"',
                        max_length=50,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="45 90% 50%",
                        help_text='HSL format: "45 90% 50%"',
                        max_length=50,
                    ),
                ),
                (
                    "sidebar_color",
                    models.CharField(
                        default="152 35% 15%",
                        help_text='HSL format: "152 35% 15%"',
                        max_length=50,
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True, help_text="Custom CSS styles", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
    ]
