# Generated by Django 4.2.7 on 2026-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="favicon_url",
            field=models.TextField(
                blank=True, help_text="URL or data URL for the favicon", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="logo_url",
            field=models.TextField(
                blank=True,
                help_text="URL or data URL for the application logo",
                null=True,
            ),
        ),
    ]
